repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: Ruff linter
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: Ruff formatter
  # - repo: local
  #   hooks:
  #     - id: dbt-lint-sqlfluff
  #       name: Lint dbt project with sqlfluff
  #       entry: uv run --env-file dbt/.env sqlfluff fix --config dbt/.sqlfluff
  #       language: system        
  #     - id: dbt-lint-osmosis
  #       name: Lint dbt project with osmosis
  #       entry: uv run --env-file dbt/.env dbt-osmosis yaml refactor --auto-apply
  #       language: system
